services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: chatapp
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  app:
    build: .
    environment:
      - ROUTER_URL=0.0.0.0:8080
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - RABBITMQ_QUEUE=chat_queue
      - DB_URL=postgres://postgres:secret@db:5432/chatapp?sslmode=disable
      - STOCK_PRICE_URL=https://stooq.com/q/l/?s=%s&f=sd2t2ohlcv&h&e=csv
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8080:8080"