// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "chat-room-api/internal/core/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GetLastMessages is an autogenerated mock type for the GetLastMessages type
type GetLastMessages struct {
	mock.Mock
}

type GetLastMessages_Expecter struct {
	mock *mock.Mock
}

func (_m *GetLastMessages) EXPECT() *GetLastMessages_Expecter {
	return &GetLastMessages_Expecter{mock: &_m.Mock}
}

// GetLastMessages provides a mock function with given fields: _a0, _a1
func (_m *GetLastMessages) GetLastMessages(_a0 context.Context, _a1 string) ([]domain.Message, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetLastMessages")
	}

	var r0 []domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Message, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Message); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastMessages_GetLastMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastMessages'
type GetLastMessages_GetLastMessages_Call struct {
	*mock.Call
}

// GetLastMessages is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *GetLastMessages_Expecter) GetLastMessages(_a0 interface{}, _a1 interface{}) *GetLastMessages_GetLastMessages_Call {
	return &GetLastMessages_GetLastMessages_Call{Call: _e.mock.On("GetLastMessages", _a0, _a1)}
}

func (_c *GetLastMessages_GetLastMessages_Call) Run(run func(_a0 context.Context, _a1 string)) *GetLastMessages_GetLastMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GetLastMessages_GetLastMessages_Call) Return(_a0 []domain.Message, _a1 error) *GetLastMessages_GetLastMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetLastMessages_GetLastMessages_Call) RunAndReturn(run func(context.Context, string) ([]domain.Message, error)) *GetLastMessages_GetLastMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetLastMessages creates a new instance of GetLastMessages. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetLastMessages(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetLastMessages {
	mock := &GetLastMessages{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
